[package]
name = "rust-dl"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "haah"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
neuroflow = "0.1.3"
tch = "0.7.2"
