[package]
name = "try-other"
version = "0.0.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
rand = "0.8.4"
serde = { version = "1.0.106", features = ["derive"] }
rayon = "1.5.1"
text-diff = "0.4.0"
husky-check-utils = { path = "../../utils/husky-check-utils" }
husky-print-utils = { path = "../../utils/husky-print-utils" }
xxhash-rust = { version = "0.8.5", features = ["const_xxh3", "xxh3"] }

[dev-dependencies]
salsa = { path = "../../abstraction/salsa" }
husky-dev-utils = { path = "../../utils/husky-dev-utils" }
serde_json = { version = "1.0.48", features = ["preserve_order"] }
